-- AlterTable
ALTER TABLE "MarketFeature" ADD COLUMN IF NOT EXISTS "returnYtd" DOUBLE PRECISION;
ALTER TABLE "MarketFeature" ADD COLUMN IF NOT EXISTS "return1y" DOUBLE PRECISION;
ALTER TABLE "MarketFeature" ADD COLUMN IF NOT EXISTS "volatility7d" DOUBLE PRECISION;
ALTER TABLE "MarketFeature" ADD COLUMN IF NOT EXISTS "volatilityYtd" DOUBLE PRECISION;
ALTER TABLE "MarketFeature" ADD COLUMN IF NOT EXISTS "volatility1y" DOUBLE PRECISION;
